<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.isjbar</groupId>
        <artifactId>minercorp-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>minercorp-gransede</artifactId>
    <packaging>jar</packaging>

    <name>MinerCorp-GranSede</name>
    <description>La Gran Sede: lugar central del servidor con tiendas de vehiculos y taladros, y una mina y un bosque publicos para ganar los primeros fondos.</description>

    <dependencies>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.isjbar</groupId>
            <artifactId>minercorp-economy</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.name}-${project.version}</finalName>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>
</project>
